### ISSUE TITLE
Wrong colors when submitting homework

### ISSUE THREAD

**Issue by andreweinkoetz** [tum-aweink/high5-learning-frontend#55]
Although the student provided the correct answers, the exercises do not have green borders:
![image](https://user-images.githubusercontent.com/14924669/41228996-acf2fa2a-6d7a-11e8-85c1-3d06bcc51161.png)

**Comment by ghost** [comment]
<img width="983" alt="bildschirmfoto 2018-06-11 um 14 10 56" src="https://user-images.githubusercontent.com/39064712/41230766-4e46c61c-6d81-11e8-9db4-d3e1058e4cf5.png">

I have fixed this bug, but it is not the optimal solution.

This bug was caused because I have used an === check instead of ==. 
Although both, props.rightSolution, as well as props.selectedChoice have the same type using === causes this bug.

@tum-aweink can you please take a look at this line 16

**Comment by andreweinkoetz** [comment]
Have you tried to cast it? E.g.:
`(props.rightSolution.toString() === props.selectedChoice.toString())`
If i use this approach it's working flawless :) Can you verify that?

**Comment by ghost** [comment]
That's it!
