### ISSUE TITLE
When creating/updating a new class, before the modal dialog closes, you can see the pure state of the component (meaning no input values etc.)

### ISSUE THREAD

**Issue by HmG248** [tum-aweink/high5-learning-frontend#63]

**Comment by HmG248** [comment]
this looks really ugly, I was sitting on the problem for a straight one hour and I couldn't fix it :(

**Comment by andreweinkoetz** [comment]
have you tried to disable the reset at the end of the submit method?
![image](https://user-images.githubusercontent.com/14924669/41346715-bea157ec-6f07-11e8-8fb3-c35d6d52287d.png)
You don't even need this as you always reset the state of the modal when the add or update classe buttons are clicked.
EDIT: Btw. it's working for me when i disable it ;)

**Comment by HmG248** [comment]
yeah, you are right, thanks :)
But one thing still isn't working: when you update a class, for a extremely brief period of time you see create class instead of update class...

**Comment by andreweinkoetz** [comment]
That is caused by setting the updateWished state in handleChangedOfClasses: 
![image](https://user-images.githubusercontent.com/14924669/41347429-ece980e6-6f09-11e8-8f7c-6bab3e09c741.png)

I think the best way is to use the OnExit event of the dialog component. I tried it in my IDE and its working pretty neat. Check it out:

1. Remove updateWished from setState
2. Create new method and pass it to Modal:
```
 handleOnExitModal(){
        this.setState({
            updateClassWished: false
        })
    }
```
3. In Modal pass it to Dialog:
```
 <Dialog
                style={{minWidth: 300}}
                disableBackdropClick
                disableEscapeKeyDown
                onExited={this.props.onExit}
                open={this.props.visible}
            >
```
